[env:esp32cam]
platform = espressif32
board = esp32cam
framework = arduino
monitor_speed = 115200
upload_speed = 57600
upload_protocol = esptool

upload_flags = 
    --before=no_reset
    --after=hard_reset
    --chip=esp32
    --baud=115200
    --connect-attempts=3
lib_deps = 
	bblanchon/ArduinoJson@^6.21.3
	me-no-dev/ESPAsyncWebServer@^1.2.3
	links2004/WebSockets@^2.7.2
build_flags = 
	-DCORE_DEBUG_LEVEL=3
	-DBOARD_HAS_PSRAM
	-mfix-esp32-psram-cache-issue
lib_ignore = ESPAsyncTCP